config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Get
  get "about-us", to:"about#index", as: "about"

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"
  
  root to: "main#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# has email:string
# password_digest:string
# 
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: {with: /\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})/, message:"must be and email"}
end

app/controllers/about_controller.rb
class AboutController< ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController< ApplicationController
  def index
    puts  :alert[0]
    flash.now[:notice]="Logged in successful"
    flash.now[:alert]="Invalid email and password"

  end 
end

 

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
       if @user.save
        redirect_to root_path, notice: "Successfully created account"
       else
        puts @user.errors.any?
        render "/"
       end
    end

    private
    def user_params
        params.require(:user).permit(:email,:password,:password_confirmation)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container"> 
      <%= render partial: "shared/flash" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to Scheduled tweets</h1>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-warning mt-4" role="alert">
<%=  flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>